version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
      cache_from:
        - mapog/frontend:latest
    image: mapog/frontend:1.0.0
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://api.mapog.xyz
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
      cache_from:
        - mapog/backend:latest
    image: mapog/backend:1.0.0
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    restart: always
