name: Auto Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version
        id: version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            -t mapog/frontend:${{ env.VERSION }} \
            -t mapog/frontend:latest \
            ./frontend
          docker push mapog/frontend:${{ env.VERSION }}
          docker push mapog/frontend:latest

      - name: Build & Push Backend
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            -t mapog/backend:${{ env.VERSION }} \
            -t mapog/backend:latest \
            ./backend
          docker push mapog/backend:${{ env.VERSION }}
          docker push mapog/backend:latest
