name: Auto Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Run bump script
        run: node scripts/bump-version.js

      - name: Commit updated version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add capacitor.config.json
          git commit -m "chore: auto bump version"
          git push
